### ISSUE TITLE
ModuleNotFoundError 'diff_gaussian_rasterization'

### ISSUE THREAD

**Issue by TheOne-king** [horizon-research/Fov-3DGS#3]
Dear authors:
     I tried to implement the code on a docker container based on Windows 11 with Ubuntu 20.06.04 LTS.
    All three steps in the Setup section have been successfully deployed and compiled. However, when I tried to run "python3 combined_training_script.py" in the docker, the error "**ModuleNotFoundError: No module named 'diff_gaussian_rasterization**'"  and "**ModuleNotFoundError: No module named 'simple_knn**'" keeps recurring. I really wonder whether you have encountered this kind of problem and earnestly hope you can provide some relevant help and suggestions.
    Thank you for your time.

**Comment by linwk20** [comment]
hi thanks for trying our work.
This is our problem, we didn't put diff_gaussian_rasterization and simple_knn under the submodules folder, let me add them.
They are cuda code from orioginal 3dgs.

Thanks!

**Comment by linwk20** [comment]
https://github.com/horizon-research/Fov-3DGS/tree/main/fov3dgs/submodules

They are here now. use pip install <their_folder_path> to install them
