### ISSUE TITLE
AssertionError: Could not recognize scene type!

### ISSUE THREAD

**Issue by TheOne-king** [horizon-research/Fov-3DGS#4]
Dear authors:
    I use the original 3DGS algorithm provided by the following link:
    [https://github.com/graphdeco-inria/gaussian-splatting](url) 
   and get the output, as shown in the first figure
![1](https://github.com/user-attachments/assets/d1729e64-9770-470f-bf97-bf65cfbb1092). The complete file is put under fov3dgs/scene by renaming it as "ms_d".
   And then, the corresponding training dataset "playroom", provided by the Tank&Temple and DeepBlending, is put in the FoV-3DGS/dataset as you have mentioned in the instructions.
   After that, when I try to running the code "python3 combined_training_script.py", it occurs that **AssertionError: Could not recognize scene type!** The complete running result is shown as followed:

   Processing scene for eff_finetune: bicycle
Running command: ['python3', 'eff_finetune.py', '-s', '/workspace/dataset/bicycle/', '-m', '/workspace/dataset/bicycle/ms_d_ft', '--checkpoint_iterations', '35000', '--start_checkpoint', '/workspace/dataset/bicycle/ms_d/chkpnt30000.pth', '-i', 'images_4', '--iteration', '35000', '--checkpoint_iterations', '35000', '--eval']
Optimizing /workspace/dataset/bicycle/ms_d_ft
Output folder: /workspace/dataset/bicycle/ms_d_ft [26/11 06:36:43]
Tensorboard not available: not logging progress [26/11 06:36:43]
Traceback (most recent call last):
  File "/workspace/fov3dgs/eff_finetune.py", line 243, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/workspace/fov3dgs/eff_finetune.py", line 45, in training
    scene = Scene(dataset, gaussians)
  File "/workspace/fov3dgs/scene/__init__.py", line 49, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!
Running command: python3 scripts/run_prune.py --pruning_metric "max_comp_efficiency" --scene /workspace/dataset/bicycle --relax_ratio "0.01" --iterations 50000 --monitor_val --path_to_pretrain_trial "/workspace/dataset/bicycle/ms_d_ft" --images_set images_4 --use_scale_decay
Original training loss json not found, running render.py to generate images.
python3 render.py -s /workspace/dataset/bicycle -m /workspace/dataset/bicycle/ms_d_ft  --eval --iteration 35000 --skip_train
Looking for config file in /workspace/dataset/bicycle/ms_d_ft/cfg_args
Config file found: /workspace/dataset/bicycle/ms_d_ft/cfg_args
Rendering /workspace/dataset/bicycle/ms_d_ft
Loading trained model at iteration 35000 [26/11 06:36:45]
Traceback (most recent call last):
  File "/workspace/fov3dgs/render.py", line 84, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test)
  File "/workspace/fov3dgs/render.py", line 58, in render_sets
    scene = Scene(dataset, gaussians, load_iteration=iteration, shuffle=False)
  File "/workspace/fov3dgs/scene/__init__.py", line 49, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!
Original training loss json not found, running hvs_metric to generate it.

Scene: /workspace/dataset/bicycle/ms_d_ft
Unable to compute metrics for model /workspace/dataset/bicycle/ms_d_ft
Traceback (most recent call last):
  File "/workspace/fov3dgs/scripts/run_prune.py", line 104, in <module>
    main()
  File "/workspace/fov3dgs/scripts/run_prune.py", line 54, in main
    with open(args.original_train_loss, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/dataset/bicycle/ms_d_ft/test_results.json'
Running command: ['python3', 'eff_finetune.py', '-s', '/workspace/dataset/bicycle/', '-m', '/workspace/dataset/bicycle/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1', '--checkpoint_iterations', '55000', '--start_checkpoint', '/workspace/dataset/bicycle/mon2_montest=True_sd=True_max_comp_efficiency_0.01/chkpnt50000.pth', '-i', 'images_4', '--iteration', '55000', '--eval', '--hvs_ft']
Optimizing /workspace/dataset/bicycle/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1
Output folder: /workspace/dataset/bicycle/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1 [26/11 06:36:48]
Tensorboard not available: not logging progress [26/11 06:36:48]
Traceback (most recent call last):
  File "/workspace/fov3dgs/eff_finetune.py", line 243, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/workspace/fov3dgs/eff_finetune.py", line 45, in training
    scene = Scene(dataset, gaussians)
  File "/workspace/fov3dgs/scene/__init__.py", line 49, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!
Running command: python3 scripts/run_multi_ecc_masking.py --masking_metric "surface" --scene /workspace/dataset/bicycle --target_loss_scale "1.0"  --ps1_loss_scale "0.01" --max_pooling_size 12 --layernum 4 --budget 22500 --path_to_pretrain_trial "/workspace/dataset/bicycle/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1" --path_to_ps1_trial "/workspace/dataset/bicycle/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1" --monitor_val --ps1_iterations 55000 --images_set images_4
Original training loss txt not found, running render.py to generate it.
python3 render.py -s /workspace/dataset/bicycle -m /workspace/dataset/bicycle/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1  --eval --iteration 55000 --skip_train
Looking for config file in /workspace/dataset/bicycle/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1/cfg_args
Config file found: /workspace/dataset/bicycle/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1/cfg_args
Rendering /workspace/dataset/bicycle/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1
Loading trained model at iteration 55000 [26/11 06:36:50]
Traceback (most recent call last):
  File "/workspace/fov3dgs/render.py", line 84, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test)
  File "/workspace/fov3dgs/render.py", line 58, in render_sets
    scene = Scene(dataset, gaussians, load_iteration=iteration, shuffle=False)
  File "/workspace/fov3dgs/scene/__init__.py", line 49, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!
Original training loss txt not found, running hvs_metric to generate it.

Scene: /workspace/dataset/bicycle/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1
Unable to compute metrics for model /workspace/dataset/bicycle/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1
Traceback (most recent call last):
  File "/workspace/fov3dgs/scripts/run_multi_ecc_masking.py", line 157, in <module>
    main()
  File "/workspace/fov3dgs/scripts/run_multi_ecc_masking.py", line 105, in main
    with open(args.original_train_loss, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/dataset/bicycle/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1/test_results.json'
All scenes processed.

**Comment by linwk20** [comment]
AssertionError: Could not recognize scene type! 
 is related to scene path configuration in 
combined_training_script.py
Can you check if you set scene path correctly and is there valid dataset under the folder?

https://github.com/horizon-research/Fov-3DGS/blob/09b652f1ded43fb8fa79e697bceb7b3f6b0e3c59/fov3dgs/combined_training_script.py#L27

I look at your error:
Running command: ['python3', 'eff_finetune.py', '-s', '/workspace/dataset/bicycle/', '-m', '/workspace/dataset/bicycle/ms_d_ft', '--checkpoint_iterations', '35000', '--start_checkpoint', '/workspace/dataset/bicycle/ms_d/chkpnt30000.pth', '-i', 'images_4', '--iteration', '35000', '--checkpoint_iterations', '35000', '--eval']

You can see that '-s', '/workspace/dataset/bicycle/' it is using bicycle dataset as config here: https://github.com/horizon-research/Fov-3DGS/blob/09b652f1ded43fb8fa79e697bceb7b3f6b0e3c59/fov3dgs/combined_training_script.py#L15
Do you have bicycle dataset there?

**Comment by TheOne-king** [comment]
Thank you for your advice, I have modified the code, and it can successfully recognize the scene now. However, it seems that it needs **chkpnt30000.pth**, which looks like the result of training halfway as if it was only iterated 30000 times. But the output of the original Gaussian results only contains the files as shown before. The required directory shows **workspace/dataset/playroom/ms_d/chkpnt30000.pth**.  But shouldn't the dataset folder only contain the downloaded data? 

Processing scene for eff_finetune: playroom
Running command: ['python3', 'eff_finetune.py', '-s', '/workspace/dataset/playroom/', '-m', '/workspace/dataset/playroom/ms_d_ft', '--checkpoint_iterations', '35000', '--start_checkpoint', '/workspace/dataset/playroom/ms_d/chkpnt30000.pth', '-i', 'images', '--iteration', '35000', '--checkpoint_iterations', '35000', '--eval']
Optimizing /workspace/dataset/playroom/ms_d_ft
Output folder: /workspace/dataset/playroom/ms_d_ft [26/11 13:26:23]
Tensorboard not available: not logging progress [26/11 13:26:23]
Reading camera 225/225 [26/11 13:26:25]
Loading Training Cameras [26/11 13:26:25]
Loading Test Cameras [26/11 13:26:32]
Number of points at initialisation :  37005 [26/11 13:26:33]
Traceback (most recent call last):
  File "/workspace/fov3dgs/eff_finetune.py", line 243, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/workspace/fov3dgs/eff_finetune.py", line 48, in training
    (model_params, first_iter) = torch.load(checkpoint)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/dataset/playroom/ms_d/chkpnt30000.pth'
Running command: python3 scripts/run_prune.py --pruning_metric "max_comp_efficiency" --scene /workspace/dataset/playroom --relax_ratio "0.01" --iterations 50000 --monitor_val --path_to_pretrain_trial "/workspace/dataset/playroom/ms_d_ft" --images_set images --use_scale_decay
Original training loss json not found, running render.py to generate images.
python3 render.py -s /workspace/dataset/playroom -m /workspace/dataset/playroom/ms_d_ft  --eval --iteration 35000 --skip_train
Looking for config file in /workspace/dataset/playroom/ms_d_ft/cfg_args
Config file found: /workspace/dataset/playroom/ms_d_ft/cfg_args
Rendering /workspace/dataset/playroom/ms_d_ft
Loading trained model at iteration 35000 [26/11 13:26:36]
Reading camera 225/225 [26/11 13:26:37]
Loading Training Cameras [26/11 13:26:37]
Loading Test Cameras [26/11 13:26:43]
Traceback (most recent call last):
  File "/workspace/fov3dgs/render.py", line 84, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test)
  File "/workspace/fov3dgs/render.py", line 58, in render_sets
    scene = Scene(dataset, gaussians, load_iteration=iteration, shuffle=False)
  File "/workspace/fov3dgs/scene/__init__.py", line 82, in __init__
    self.gaussians.load_ply(os.path.join(self.model_path,
  File "/workspace/fov3dgs/scene/gaussian_model.py", line 455, in load_ply
    plydata = PlyData.read(path)
  File "/opt/conda/lib/python3.10/site-packages/plyfile.py", line 157, in read
    (must_close, stream) = _open_stream(stream, 'read')
  File "/opt/conda/lib/python3.10/site-packages/plyfile.py", line 1347, in _open_stream
    return (True, open(stream, read_or_write[0] + 'b'))
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/dataset/playroom/ms_d_ft/point_cloud/iteration_35000/point_cloud.ply'
Original training loss json not found, running hvs_metric to generate it.

Scene: /workspace/dataset/playroom/ms_d_ft
Unable to compute metrics for model /workspace/dataset/playroom/ms_d_ft
Traceback (most recent call last):
  File "/workspace/fov3dgs/scripts/run_prune.py", line 104, in <module>
    main()
  File "/workspace/fov3dgs/scripts/run_prune.py", line 54, in main
    with open(args.original_train_loss, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/dataset/playroom/ms_d_ft/test_results.json'
Running command: ['python3', 'eff_finetune.py', '-s', '/workspace/dataset/playroom/', '-m', '/workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1', '--checkpoint_iterations', '55000', '--start_checkpoint', '/workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/chkpnt50000.pth', '-i', 'images', '--iteration', '55000', '--eval', '--hvs_ft']
Optimizing /workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1
Output folder: /workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1 [26/11 13:26:47]
Tensorboard not available: not logging progress [26/11 13:26:47]
Reading camera 225/225 [26/11 13:26:48]
Loading Training Cameras [26/11 13:26:48]
Loading Test Cameras [26/11 13:26:54]
Number of points at initialisation :  37005 [26/11 13:26:54]
Traceback (most recent call last):
  File "/workspace/fov3dgs/eff_finetune.py", line 243, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/workspace/fov3dgs/eff_finetune.py", line 48, in training
    (model_params, first_iter) = torch.load(checkpoint)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/chkpnt50000.pth'
Running command: python3 scripts/run_multi_ecc_masking.py --masking_metric "surface" --scene /workspace/dataset/playroom --target_loss_scale "1.0"  --ps1_loss_scale "0.01" --max_pooling_size 12 --layernum 4 --budget 22500 --path_to_pretrain_trial "/workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1" --path_to_ps1_trial "/workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1" --monitor_val --ps1_iterations 55000 --images_set images
Original training loss txt not found, running render.py to generate it.
python3 render.py -s /workspace/dataset/playroom -m /workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1  --eval --iteration 55000 --skip_train
Looking for config file in /workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1/cfg_args
Config file found: /workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1/cfg_args
Rendering /workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1
Loading trained model at iteration 55000 [26/11 13:26:57]
Reading camera 225/225 [26/11 13:26:57]
Loading Training Cameras [26/11 13:26:57]
Loading Test Cameras [26/11 13:27:03]
Traceback (most recent call last):
  File "/workspace/fov3dgs/render.py", line 84, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test)
  File "/workspace/fov3dgs/render.py", line 58, in render_sets
    scene = Scene(dataset, gaussians, load_iteration=iteration, shuffle=False)
  File "/workspace/fov3dgs/scene/__init__.py", line 82, in __init__
    self.gaussians.load_ply(os.path.join(self.model_path,
  File "/workspace/fov3dgs/scene/gaussian_model.py", line 455, in load_ply
    plydata = PlyData.read(path)
  File "/opt/conda/lib/python3.10/site-packages/plyfile.py", line 157, in read
    (must_close, stream) = _open_stream(stream, 'read')
  File "/opt/conda/lib/python3.10/site-packages/plyfile.py", line 1347, in _open_stream
    return (True, open(stream, read_or_write[0] + 'b'))
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1/point_cloud/iteration_55000/point_cloud.ply'
Original training loss txt not found, running hvs_metric to generate it.

Scene: /workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1
Unable to compute metrics for model /workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1
Traceback (most recent call last):
  File "/workspace/fov3dgs/scripts/run_multi_ecc_masking.py", line 157, in <module>
    main()
  File "/workspace/fov3dgs/scripts/run_multi_ecc_masking.py", line 105, in main
    with open(args.original_train_loss, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1/test_results.json'
All scenes processed.

**Comment by linwk20** [comment]
yes. we read ckpt instead of .ply, so you need to either retrain one and specify 30000 in ckpt_list to get the ckpt, or modify our code to read ply.

see if our provided model contain it: https://drive.google.com/file/d/1H2XhS1Jh-Pd-W8NvA4Z0bLlUADcJhAj5/view

**Comment by TheOne-king** [comment]
The error mentiond that **/workspace/dataset/playroom/ms_d/chkpnt1500.pth**
So should the md_s file, which contains the dense Gaussian model,  be put in the dataset folder instead of the scene folder?

And I tried this way, it seems to work for now.

**Comment by TheOne-king** [comment]
It seems that it can complete the training part now. But after the training stage, it comes to the metric computation, and it occurs the error of not finding "**test_results.json**". And it also mentioned that there should be a file "**chkpnt50000.pth**" under the **/workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01**. I have checked the directory, the program does generate the folder but without the file **chkpnt50000.pth**

Scene: /workspace/dataset/playroom/ms_d_ft
Method: ours_35000
Metric evaluation progress:   0%|                                                                | 0/29 [00:00<?, ?it/s]Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /root/.cache/torch/hub/checkpoints/vgg16-397923af.pth
 41%|████████████████████████████████▊                                               | 216M/528M [03:07<04:29, 1.21MB/s]
Metric evaluation progress:   0%|                                                                | 0/29 [03:08<?, ?it/s]
Unable to compute metrics for model /workspace/dataset/playroom/ms_d_ft
Traceback (most recent call last):
  File "/workspace/fov3dgs/scripts/run_prune.py", line 104, in <module>
    main()
  File "/workspace/fov3dgs/scripts/run_prune.py", line 54, in main
    with open(args.original_train_loss, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/dataset/playroom/ms_d_ft/test_results.json'
Running command: ['python3', 'eff_finetune.py', '-s', '/workspace/dataset/playroom/', '-m', '/workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1', '--checkpoint_iterations', '55000', '--start_checkpoint', '/workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/chkpnt50000.pth', '-i', 'images', '--iteration', '55000', '--eval', '--hvs_ft']
Optimizing /workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1
Output folder: /workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1 [27/11 05:38:12]
Tensorboard not available: not logging progress [27/11 05:38:12]
Reading camera 225/225 [27/11 05:38:13]
Loading Training Cameras [27/11 05:38:13]
Loading Test Cameras [27/11 05:38:19]
Number of points at initialisation :  37005 [27/11 05:38:19]
Traceback (most recent call last):
  File "/workspace/fov3dgs/eff_finetune.py", line 243, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/workspace/fov3dgs/eff_finetune.py", line 48, in training
    (model_params, first_iter) = torch.load(checkpoint)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/chkpnt50000.pth'
Running command: python3 scripts/run_multi_ecc_masking.py --masking_metric "surface" --scene /workspace/dataset/playroom --target_loss_scale "1.0"  --ps1_loss_scale "0.01" --max_pooling_size 12 --layernum 4 --budget 22500 --path_to_pretrain_trial "/workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1" --path_to_ps1_trial "/workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1" --monitor_val --ps1_iterations 55000 --images_set images
Original training loss txt not found, running render.py to generate it.
python3 render.py -s /workspace/dataset/playroom -m /workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1  --eval --iteration 55000 --skip_train
Looking for config file in /workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1/cfg_args
Config file found: /workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1/cfg_args
Rendering /workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1
Loading trained model at iteration 55000 [27/11 05:38:22]
Reading camera 225/225 [27/11 05:38:23]
Loading Training Cameras [27/11 05:38:23]
Loading Test Cameras [27/11 05:38:28]
Traceback (most recent call last):
  File "/workspace/fov3dgs/render.py", line 84, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test)
  File "/workspace/fov3dgs/render.py", line 58, in render_sets
    scene = Scene(dataset, gaussians, load_iteration=iteration, shuffle=False)
  File "/workspace/fov3dgs/scene/__init__.py", line 82, in __init__
    self.gaussians.load_ply(os.path.join(self.model_path,
  File "/workspace/fov3dgs/scene/gaussian_model.py", line 455, in load_ply
    plydata = PlyData.read(path)
  File "/opt/conda/lib/python3.10/site-packages/plyfile.py", line 157, in read
    (must_close, stream) = _open_stream(stream, 'read')
  File "/opt/conda/lib/python3.10/site-packages/plyfile.py", line 1347, in _open_stream
    return (True, open(stream, read_or_write[0] + 'b'))
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1/point_cloud/iteration_55000/point_cloud.ply'
Original training loss txt not found, running hvs_metric to generate it.

Scene: /workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1
Unable to compute metrics for model /workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1
Traceback (most recent call last):
  File "/workspace/fov3dgs/scripts/run_multi_ecc_masking.py", line 157, in <module>
    main()
  File "/workspace/fov3dgs/scripts/run_multi_ecc_masking.py", line 105, in main
    with open(args.original_train_loss, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/dataset/playroom/mon2_montest=True_sd=True_max_comp_efficiency_0.01/hvs_reshape_ps1/test_results.json'
All scenes processed.

**Comment by linwk20** [comment]
Yes. chkpnt50000.pth is the pruned result of the first layer.
The FR masking will need to use it for metric generation, and the metric will be used for the following quality monitoring in FR masking.
Thanks for your interest!

**Comment by linwk20** [comment]
I just checked the code, seems that we should save the result at last iteration (50000)
See: https://github.com/horizon-research/Fov-3DGS/blob/09b652f1ded43fb8fa79e697bceb7b3f6b0e3c59/fov3dgs/prune.py#L379

**Comment by TheOne-king** [comment]
Really appreciate your help!!

The last question is if I only want to focus the prune stage, instead of the "scripts/run_prune.py" and  "prune.py" is there any other scripts I should pay special attention to?

And if I just want to see the evaluation metrics of the pruned result, which one should I focus on? As it seems will give me two evaluation metrics during the execution of "combined_training_script.py". 
![issue_1](https://github.com/user-attachments/assets/748f69ee-f266-4b9d-b383-7de3f9aa850b)
![issue_2](https://github.com/user-attachments/assets/da32f30a-75ee-49ca-ab8f-76249bf3b63a)

Thank you for your time and patience!

**Comment by linwk20** [comment]
The second one, the first one is before pruning.
if you only want to focus the prune stage prune.py is the only one you should focus.

Thanks for your trying!

**Comment by TheOne-king** [comment]
Thanks a lot!! Really amazing research!
